alias vi='nvim'
alias ls='ls --color'
alias l='ls'
alias ll='ls -al'

export PATH="/opt/homebrew/bin:$PATH"

# git autocomplete
# curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash
# chmod u+x ~/.git-completion.bash
if [[ -f "$HOME/.git-completion.bash" ]]; then
    source $HOME/.git-completion.bash
fi

# setup bash completion
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

# kubectl completion
source <(kubectl completion bash)
alias k=kubectl
complete -o default -F __start_kubectl k

[[ -f /opt/homebrew/opt/kube-ps1/share/kube-ps1.sh ]] && . /opt/homebrew/opt/kube-ps1/share/kube-ps1.sh
KUBE_PS1_SYMBOL_ENABLE=false
KUBE_PS1_NS_ENABLE=false
KUBE_PS1_CTX_COLOR=cyan

# kubectl-krew plugins
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
alias ctx='kubectl-ctx'
alias ns='kubectl-ns'

# prompt inside a git repo
# git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1
if [[ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    GIT_PROMPT_THEME=Custom
    source $HOME/.bash-git-prompt/gitprompt.sh
fi

# prompt outside of git repo
PS1='$(kube_ps1) \[\033[0;35m\]\u\[\033[0;37m\] in \[\033[1;32m\]\w\[\033[0;0m\]\n$ '

# fuzzy find: https://github.com/junegunn/fzf
[[ -f ~/.fzf.bash ]] && source ~/.fzf.bash
# ripgrep   : https://github.com/BurntSushi/ripgrep
# autojump  : https://github.com/wting/autojump
[[ -f /opt/homebrew/etc/profile.d/autojump.sh ]] && . /opt/homebrew/etc/profile.d/autojump.sh
