#set -g default-terminal "screen-256color"

# vi keys
set-window-option -g mode-keys vi

# split panes using | and -
bind | split-window -h
bind - split-window -v

# navigate panes
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r h select-pane -L

# resize panes
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R
bind -r H resize-pane -L

bind C command-prompt -p "New window name:" "new-window -n '%%'"
bind W command-prompt -T "window-target" -p "go to window:" "select-window -t '%%'"

# Enable mouse mode
set -g mouse on

# Use a 12-hour clock in clock mode and the status bar.
set -g clock-mode-style 12

# theme
source-file ~/tokyonight_night.tmux
# source-file ~/tokyonight_day.tmux

# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
